galaxy_info:
  author: Sam Doran
  description: "Install internal Microsoft CA certificates"
  company:
  license: MIT
  min_ansible_version: 2.2

  platforms:
  - name: EL
    versions:
      - 6
      - 7

  galaxy_tags:
    - system

dependencies: []
