- name: configure external logging to elk
  uri:
    url: https://{{ ansible_default_ipv4.address }}/api/v2/settings/logging/
    user: "{{ tower_username }}"
    password: "{{ tower_password }}"
    force_basic_auth: yes  
    method: PUT
    body_format: json
    headers:
      Content-Type: application/json
      Accept: application/json
    src: templates/elk.j2
    validate_certs: false
    return_content: yes