- name: remove org - default
  tower_organization:
    name: "Default"
    state: absent
    tower_verify_ssl: false
    tower_username: "{{ tower_username }}"
    tower_password: "{{ tower_password }}"
    tower_host: localhost

- name: create org - red hat
  tower_organization:
    name: "Red Hat"
    description: "Red Hat Consulting"
    state: present
    tower_verify_ssl: false
    tower_username: "{{ tower_username }}"
    tower_password: "{{ tower_password }}"
    tower_host: localhost